CMS Security Fix
Science37/isbx-loopback-cms pull request #29
Opened 2019-05-03 05:34 UTC by s37-robert

Restrict the /cms/model/save endpoint, allowing it to only modify those tables which are absolutely necessary to the operation of NORA. Eventually, we want to retire this entire library along with the rest of NORA Core.

The list of allowed tables is hardcoded. There's no need to take the additional risk of storing this in configuration since the library itself is deprecated and is being restricted as part of its end-of-life plan.

2019-05-03 05:38 UTC, s37-robert commented
Note: To test this in Cloud 9, you must do the following:

modify package.json to set the branch name for isbx-loopback-cms

shell into the container
`docker exec -it $containerId bash`

force install isbx-loopback-cms
`npm install isbx-loopback-cms --force`

restart the server
`touch server.server.js`

2019-05-03 05:40 UTC, s37-robert commented
Recommended regressions:
Look for ways to use cms to save the following high-risk object types:
- Lead
- Site
- Sponsor
- Vendor
- Contact

2019-05-03 17:39 UTC, beekley approved these changes

2019-05-03 21:32 UTC, s37justin approved these changes

2019-05-03 21:47 UTC, kiran37 requested changes
Following pages will fail if we merge this change:
1. Clinical Trial create/update. [Trial is not on the whitelist]
2. Patient Create/Update [Create Patient still uses CMS endpoint on the frontend, and it hasn't been updated to reflect the API change]
3. Patient Trial Setting [TrialAccount is not on the whitelist]

We probably need to make all the frontend changes before we make the backend restriction on CMS

2019-05-03 22:17 UTC, s37-robert commented
Updated PR to add Trial to whitelist.

We can't add Account or TrialAccount to the whitelist because the CMS fix explicitly requires that we block those models. Tickets   PC-1891 SUBMITTED  and   PC-1892 SUBMITTED  have been created to update the frontend to use the new endpoints instead of /cms/model/save

2019-05-03 22:30 UTC, willdrewess37 approved these changes

2019-05-07 20:50 UTC, kiran37 approved these changes

2019-05-07 20:54 UTC, merged